<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class SendDummyNotification extends Command
{
    protected $signature = 'notify:dummy {email=student@campusos.com}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Send a dummy notification to a user';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $email = $this->argument('email');
        $user = \App\Models\User::where('email', $email)->first();

        if (!$user) {
            $this->error("User with email {$email} not found.");
            return;
        }

        $title = 'New System Update';
        $message = 'This is a test notification generated by the command. Time: ' . now()->format('H:i:s');

        $user->notify(new \App\Notifications\DummyNotification($title, $message));

        $this->info("Dummy notification sent successfully to {$email}.");
    }
}
